---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: openebs-hostpath
