apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:yxVRKyttSbK5qu5dIU/AFpqdABjf1Olw1KmTY5pU3SVn0zSt,iv:d1tH6mRAEZwleZmGC0k5Z49iJrti3Xhe9rXZl0Z3v8w=,tag:Xbb5Vmul+42NTYqhyu17Pw==,type:str]
    credentials.json: ENC[AES256_GCM,data:ncHWN6+yBPbOUAY30jejrbrY7DXMiui3JDLoW7OqOzE5Br55ccxOh+ziqI2SVNR30OQqz3NAXrB1nFsrXvGpJzvmn/0ZApZcf+O7X6FYJQ3hnGB+Qdvz2HbkGm6FzKBAMz8sFbxw5jqzpYkQ6uZvYCFmEYD8y8ETTbQ9XXfplW0XQuqAAXeE4KddpK1I1U69gI0ABToeoXIn2bdfRoNOSmmv9mdpmtdtZvZRqbSX1A==,iv:ChkGhApaQEA/sy2yFd3wZp6f+YVn5V2lR11vp/9cFBU=,tag:Um1iZENpwsxTO6OxUIbgSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM3J0aFYvVGZmSU15NlZU
            U2pqNDNWeEprODBqWE9FVlVzWFRZRzJ4TUZJCi9OeC8vZFNxSTJ0UUpQcTdPQ29y
            RG5EaTNPSWw1bXdpTGdabVQ5SXFxd0EKLS0tIHp4MDQ4ZXBqd21uN08ycWdCZTNQ
            K3E4aVIrMmZwWDFxYzNENVdmRm1DT28K7QpDtZbCoTPdm7XTydf6VNQAzH963sN8
            HF4ILNi5PxQQtWrTkqGH+Pfwhc1dgi2NDBC1bg4Dh7kRJZ2Vj2IArw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T14:36:17Z"
    mac: ENC[AES256_GCM,data:RVGVVXr3oVvmZaG3Y1VxgIBY13E8ZMlhvVUnS7uZrD7QcnYgYvoK3BnbcDZuBMou1TmaGe4chZJIE53vpJk5Nw8tGRND5mMF8VQyni08klgl0zD3NawFsf8ngmB+jJc/yD3Y3G+7YF2FmkAt9ed31aapYtoOBMgmkJ1ZE2DxdiY=,iv:hNENwx32LD7GqvDsRpKKOwnluXS5w0058zcZ9s6m5fw=,tag:8DssrsMm14abG2Kmnwx7oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
