apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:k1Y6ye+27YYdd+wqES8eRuoyNSdX1Jd1E5W/gnyM9FT4/hq/,iv:xe2DMazLsVCNQvYbAHXr+srsKXpMAGCnXWE1AixaMYw=,tag:xM9Cs7/cGbfaej3DHtvleA==,type:str]
    credentials.json: ENC[AES256_GCM,data:tokG0C/jrahyVNCrA+H3zNteRkbFZkormtSU7uEa4CdwCGd22gsZr1tPZ41z+UYA7ZcGfvifUS00eO5n8ha/ZgqDm8slBT/MV6w7z9r40v1xX9rIjJhC69E+KieXNp1LMV7Hv8/cjIUE4XyVFPI+CqXmjUt87VfOK59As4LvadZdB+d21UlQrFeeNDCYssxYHeCdxaLFAZDlh0lrBhXQpGb9410g19iM2I95dagr4A==,iv:P8t4+qcOPktJxksOpfp13MgJDt8aE40fxTdjrrIhJ5c=,tag:ytTCL5P31HGgw9PZyaCmmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S1paaFVaUVJzL1ZwTyto
            Q2x1ZkR0OG1raHpOQ2x3azFSY1l5eG1iRmx3ClNTdkRMdGxVMXlLQkdTYXczM3VD
            Y2NhMndGdDBrNXkzZk9DUVhHK1M3c2cKLS0tIEEvcGxwZFVZR2F5REttWHJwRDNz
            L3JlSmJvSkFETmpRTHhNekk1dXN4NWcKaigoYv3TRF/AN4Y5Z0SFxWg1CaJntEFn
            LUdLckN+StTnRh5Qta9kS6Qt5idiFNG/y6CtbMpj14qAIhr83I61tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T08:44:50Z"
    mac: ENC[AES256_GCM,data:+yeuJN+qjnIW8lSGRfk6NFXbRfqcYL9aavyH+3ABO6rwXKBiNh/+BIiqoPrXh1/kSMQykje2LJqO1v5SgICI55dkoBPmZ1kuOVOe1zTdlyi27Kn23MbsN7iY1skNo+KnjQVvmex0O5nrsrQH2JY6kQubzcC8wKRvNITFpAUHsZ4=,iv:N0uzKEKpHpf3JpLo309MM6YIiuDyd2+nnRR+VxjAQE0=,tag:g/D/ztVSYe4Xw7xkM6wQQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
