apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hfn+IO48Ozz5CKGxgN+jO3Npt+A9KKZThD9WBXbImF129vR/,iv:NP1gaISJy3Yt7St19oViPNLZFWN1mZHb4crNG+u2EF4=,tag:l10UQuTFwMiSYQRh5nZBlQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:r0Ydpa2QotDZVhvhT+O8KF4Lccu0RweOVHOYofq7SH3zzEPhaYpuUqzsFzsITSQrgEG+dPn089Bdb85olOMrKSCsIJ5AMUXcXsMnerqJb/a2ZWALhY9P5CP9kIFrIO/LEplZMoSrdTKoZU7T8UPYGk43E+Ntpu0Hppis3MuHd4AJEovFRBYDkxVms+/8cAVkSjqqEbyEvQt8C65vkxZmjvYWtPcrFrodnkNBleZn9Q==,iv:J88t5/eQ6FnJhKHrzTeFFUB+/AQTqndO8zdPnGnb8vA=,tag:FhA4Td5asDYuX3Y6L5Y6OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbFYzSnR1TkNtTmpIU3By
            MEtKNHVQMWgxNVVOSTY3WHp4cUxBTERqUlRZCjR4T2RrZW94RENHc3dtYUY5eFh0
            L2I4NnZyU1pyaTY3WmZoSk9Bc1NKR0kKLS0tIG5HM2JaQVkwdG5aMjJWUWNJRkUz
            MUV2c09wNTBPenlhNDZYRFR6VzVjTW8KVWmAUFp5MW2Hvgtyfo3lntWs6O/37+Ly
            +BlSxoQ7S11+GSj8JqCY9nxUZXyP3zmN6p065tz3nQMWb37ZAu+jhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T16:17:15Z"
    mac: ENC[AES256_GCM,data:o/LyyP821WlfFrkGkfwsfQ27u8otBhaXqaC775aZ5/mptFKKh4LMFKbInHR1sYE0/Y1YY2IY57mYaqQch9Epzp+e7yP0dNbIiWII33WAiWIOgrgAkoOaNT6cMph171oy8h4ubvItboELYNTY60k3+61QLRzW64jQ0qMFQYp6Bgc=,iv:Llbfk4QsdfWHmjtp3sQ6Fdkxe2kAMuAH2Zf/R8kNNRI=,tag:xVe5RfygG3gNnLyWrYjcCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
