# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ollama:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.5.7
            env:
              OLLAMA_LLM_LIBRARY: "rocm"
              LIBVA_DRIVER_NAME: "iHD"
              ONEAPI_DEVICE_SELECTOR: "LEVEL_ZERO:0"
              SYCL_CACHE_PERSISTENT: "1"
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_MODELS: /data/.ollama/models
              TZ: Europe/Amsterdam
              OLLAMA_INTEL_GPU: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 11434
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            volumeMounts:
              - mountPath: /dev/dri
                name: dri
            resources:
              requests:
                cpu: 200m
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
        volumes:
          - name: dri
            hostPath:
              path: /dev/dri
              type: Directory
    defaultPodOptions:
      securityContext:
        runAsUser: 1000  # Standaard non-root gebruiker
        runAsGroup: 1000
        supplementalGroups: [44]  # video group ID (check met `getent group video`)
    nodeSelector:
      gpu.intel.com/i915: "1"  # Zorg dat de juiste GPU-node wordt gekozen
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: gpu.intel.com/i915
                  operator: Exists
    service:
      app:
        controller: ollama
        ports:
          http:
            port: 11434
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /data/.ollama
      dri:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
