apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0E/OsZXPljlBcqPDp6QQPERXIv4oU+yFQ89dR8+FVpjdr5czqyCVVg==,iv:CQ9XAzgd6Flx99vcxr+IHPaPlZ8oXu15u6cj4m/hX7M=,tag:udDKkR/vA1caeL+bJBh3bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSlNTc3FxTFVpOXdBUmhi
            c2ZjV3Jzcll6SkxKbkxWQnJvN2xDTVNKMjFzCm4vTmZuQUMvR0RMWnpXMHRDcnVY
            Yk5IanZaRzdNTHVHVGZKRnRNRmp1c0kKLS0tIHFYNytmWTR6K0tBWE9EbmJGZ0Vv
            OS92c2hqc3YwcjdVeWEwcUtXL25yVHcKVHXoRpvbPHmNIjhx6l/yoroU3X66EjMH
            yax5yHRt6Pl4xGeF6VVDymHnyIqpXBicoGGF/V4jFad3z539YT6iwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T15:44:54Z"
    mac: ENC[AES256_GCM,data:d/fmcwKu2mNR8seJ1Zjezu9Jns4RhO8OmRshuK4WnZMqvnQ272VoH4MaRUGd935BepIbrMRWP7csISSHYT8MC8yIIEi264VJUX2BkC2yiDlfZ91wk5D6yZsl44LLJBUOfQgvoQd8NYUZo7QqmG+ljpmTbkaxgg+6+6GhasmRlbo=,iv:ShQZPdzm7PJXwP3sldOJfjwZarviinUkoGckbskZOvo=,tag:haGp1zo+u1fFdFcL3lp9Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
