apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ddtHzq1EbyQwRiq9/A9z9aPK5ralOPX6/oHWqsL67+EOvrVhActphA==,iv:RTnYxyZCvQjhL5Q30CuSLWe7YY48UYw4dztem+Kj9J8=,tag:1rG0JrWvXX2oULFGqd+pvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOFR3dEI2Q0JtYThZY2JT
            OGpxL2dLVGxPNDJORTlqdXBKSHA0dFkwT1dFCjlZWHF1eUNDMTNWUlBzTXgvS0Rq
            eFlGY3RyVFBUdWJXNVk0MERvRFlnUk0KLS0tIGFSYXA4Qit4ZTE1a0pBUk9hSXZi
            Zk82Ym1XTW1BWWQ2YzRDVlZSV0lWSTgKIrBjAxLxy/P7gZeQpk8Jh29GHbNgDjBh
            r5Ygvc4cHQyQUMdynyriOtXPUuerFK+iTxCGY1NZ1+eK4QMCQxh3Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T14:07:17Z"
    mac: ENC[AES256_GCM,data:axi32j5D4vHvV2DhPMrrZIzPAD3O2RDQtESovYJzJa0V55D7juOuEuhSZ6ZWQheZsNXwz3Eu6ohuMvWGVFW7PIFEi0VKx28P/xexaAjLy0K3jfp1wCx3fbVQKE8egVbztmRyLGgwtBQe1c5SnA6DfnD1vPoF7saWp10ACHy0Mkw=,iv:JiPDFNT6l90MEdZB2IxRhC4fgLnutZt6WW0XnxAlXd4=,tag:MIUgTPgSy9DwJ0ILSxtbOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
