apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:LjPbPfhCaO1tMcEX4iPmtN6tGJxmdLt9sWn7fToBEpqR/ETFbRK1tQ==,iv:UQxxn3MxlXDpWtP3wMAzRobEbQrM2K605kgqBtt6hC8=,tag:TVQtQdPmu0ZsDu6w20Aejg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SmpVQ3pjUFlqUVdpWFla
            dU8vL2FqRng4UVpuU2U5RXVEUzZVODhrbmdjCldyWWFKdGxSRlVkWi9BMCtYeDdL
            QTdUTXhFNEVzNEkrRzcyVFJzL09aNG8KLS0tIHZRdVpXaGRCQ1BlaWloOGxSVTd1
            bXNYZUZwYk9CQXdoSlpYakgvbVRqZEkKuhQjAiGm9UOFWz+0Nl+Z4Os6CwM8qqA/
            IFXpO63kdRB7L8wv2vI7gjw7DpGU24YMWMVT3SBSJH7syR+e4Sy6Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T08:49:30Z"
    mac: ENC[AES256_GCM,data:FmD+PzqV9Iq7kJYiVYw7UMYU8LrlWlzzUDoLyk2BbPvRIfFeSSaiXrqHt8E+zFBBBKReCUI+JObwcPBd+9D9QMHKmSGRtEkKcTD5RHTX4L3cQQTMAHE+Yk/bCgwv3ZyP722GIGkCrSkpU341EpmdCNrJysVE2wK2ThngBPI7k0U=,iv:HfkAq5IXDn4UIGTqBwg04cNXnFRDkzG3/kf2/HJNuYw=,tag:nhswO9C4fiZBU6hmAMdG3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
