---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bazarr/ks.yaml
  - ./calibre/ks.yaml
  - ./calibre-web/ks.yaml
  - ./echo-server/ks.yaml
  - ./freshrss/ks.yaml
  - ./hajimari/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
# - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml

components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: default
    target:
      kind: Namespace
