apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zaHJNBsxc3dl,iv:WSKBke254SeCdeCpUh8CPhu9jBrp5EA+QmorIP93Wwo=,tag:NgTwQgVUiIVYKwOpc85Lsw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:i9TCzhgDVuvBxSjHxmpu9eakg3c=,iv:u9PnHuUCq5SHX5jLLfMM9JVtCR57A2v4qmk9LTqg348=,tag:0/a1b0ZaChDTvOZKkZaPTg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6J7YS8kRvjDrsSWOWOlzzjKEKakyUpqg+hDWNRdEHOc1iNnr,iv:zTWkwpbHjz3/daoPzy0wUey6T7usFDQaz5d4PrHsCUc=,tag:vlwJxLdFZlxFtw90H/8fTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKckFXNWlYRm1zbThFVm1s
            NHI5NWFIa1NIWFBmaHJTaHVuZndVWHN4Tno4CllwVGI1bDhCbWpweXU5TzZkeDVG
            ZUtWR1htSEdnUmp5MHV0RHAxVnFuK2sKLS0tIHJLeUFQL3RGc3RXMlFxSEdKYUk5
            ZUxHSS8rZmNLZS9JZmVHL2EyeDgxblEKP8TfK2v2Ap/Bt9xFqPiNaLGyc8R5GR1g
            0YyeIoPMGjcev0uD7aFzbt95b4bma6ffk1pIiw78kKorq0XpC0Z9WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T14:07:17Z"
    mac: ENC[AES256_GCM,data:A4KuGFkaQKXF1PM81Qx9LSfWS1X+OeTVoC2oEgTrneZLJne7R7jmPAoUTmMQUgHPz8gGlMVphDPKMNMP5CJX1e2DTFNCtkdk9oiwjVyiPEZ6uuPKBHhNJc6Aw9aNvrCYSDcDoE5ORWrX1AhPBO1Nw6yl+gCo1oInvPC1ibLsI4g=,iv:8mmvpTwpQBgsORh30/7M/XDitMNoJaUUYGLQzj87Wl4=,tag:kC76+FRcLp/2I6fVDGbVXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
