apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BMn2m3NFkjEi,iv:asxuPjbqWK/rwSGXeYaliF4wAXAS8Y3gcJ0PkXnahUI=,tag:gNFDCjWwY0FbvNbQGl88LA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OYnt+bwLg/onMEdJcGx74fcA1nk=,iv:jrf04DtL7J/FdwXNGTZ9ckSCPWccR+aOjqy0XvQu9Lc=,tag:cgviqQyvI/9VaOiYysLv0w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VPA4agS4jNi0jo5XBq2CoMcRtI0H6yjQ7grCariCLxp3JmvP,iv:TqSFzU1MGAMjzuW5wOBhsvXLHCkbtD8oWo8qi4t9v1s=,tag:kjqUog9SwLK+vtigdkv0rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYlovUDZqakxDNmQ5U1dv
            SlJOR3BTc2Fwc0NkSjF0eDZKNHAwckZoRkE0Ck9nNVVkSTdUTnVYK1d2NWdXNWwr
            WUlpbTlUYUpLVStyVjZ3bnE4MmlhMzAKLS0tIE1jQlZUOW4zTi83ZFJUUk5neG11
            dlB1ZWlEdmUrZXR6QytnN0J2c1lYdkkKOcs3tOuGUe3sURcJSdht6yBKkps9rDsN
            s7wnugqsph1ybTrWCjD6c5a+y7CZ2TEoZ6kjTTzveBvyk+EKddrquw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T16:17:15Z"
    mac: ENC[AES256_GCM,data:gtYQY68FmMY1AVppBY5XDeM97oMYB4dTnHbknFWwv3Fny2dGLgGKXy7L94QOX4iG6YIaE/xjqe6iVOx5IC9TQMOomY3uvD0PF/liRYCRLzlkDeaOgUxWaH+vPLZejp/gV1idHhEYf3xnEJnTmR0sEPxhwASc/S1JOrQezhKBJ+E=,iv:NeA1cHiCZx2bXySZ8FyuhE+JQEBQyAlQhhc9V6WqqJ4=,tag:34Da9c4l4r3xxXSkmQxUkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
