apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N9cOouxz9VwA,iv:PBu6uWeH8f/Yi0DrJFa/on44xysOipE4+daShjtFhBo=,tag:cwCmCJ9vyvYGVxm+Y4btRw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:r/sCvo1HWH7DBiqwAzRnxn41Ov8=,iv:jKh+lTkhfQGOx20B6CkJxqleyVsJyDaPt/KoIDLqgtw=,tag:W7H6ErqWYM0qrltUS0coiw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:dZdedYiJWajYt9JQ0SAWIQyswcT2OUMsgzSiWgur7hN5zeuA,iv:kWT7cH1T1lnltyAeXyk0nXYCuIsz0QdOUNBKqE2iDs8=,tag:PIsD0i7vk7/cJXvfZA5L6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckQzUFVvcy90eHY3bUJ6
            dzkyWW9scDVsUDE2eG5HcWJMclR2QUdHeGtRCkh0QjJCUFRvcVg4R09HWGo2S1lr
            eEhuK1hIZ1dXZk9JTnVtMGFnTm1DTVkKLS0tIGU0K2xJRlhTeFI2c3g0cGFhRm16
            c3NlSHFWQVUxMGthVkFGTmJSYmdkem8KM3R3TifksQObTtT+7XLdenwCabO51Fco
            A7HHQn5uT5Iv0LSF0Uvo1/Hu98f2i7vUkSUgrIJ1Q8OV7tcfiRCIwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T14:32:00Z"
    mac: ENC[AES256_GCM,data:Tzlu7JGq525EewVwFY+S9+VSmSwj7zDuV4rlXoNUyVKjjuxEO9KeY1dqI3k5UCfAz3yCveoEjknIPtWQWYL6fPmdDDEveId/l7slq3ad9+dLD/ajTnhulDAAJlvIQPcSm/zMliBmTd6SoosKbdTZyeEjE5FadcDcNGUymjB7QdI=,iv:Bp+85hsl7ReqG9QiYCmkN//n9SX19Z3e1cqWWnpffBo=,tag:OlrEbrBexIleVzIvXvv20A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
