apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4TmPFCNs7jwgvSyjH3V35IFawtz8pMBDJyJWPwhHEQ0=,iv:UNerGmGQaYrwzLTFbHAPLr7piSkGxmTejm0kCDbUamU=,tag:bFANpAVVgsRzl3O8F255qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbkdFQXJEOTdmRzZObVI2
            RENsOVBFdndORnArc3B6UDRBVmFlazhHSlJNCkp3WjdFejRpOVRwcTBDZmNtL3Ru
            VlVCQ2dncTh5MzBhL2xuOWJadExXZFkKLS0tIGprUEl3bW15NU9YS3lWK25DYnFN
            S0tMaGpKQjlLK0NKd2FSSnZPMHVVZEkKd+wn0ooWMy/ysIdOhwnHlSv8TaTO4Nzq
            RR83+hE+MCYJdsTtut/ztlnvKIfAvAcXHMRj0i0q/bsf535Po0Uymw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T15:44:54Z"
    mac: ENC[AES256_GCM,data:yYPXSotPLlVgDGHBF9Vmy9N6OMxCHcWia70QXRs+lXhnZGCpi3hKjZLmhi9hyI7VMaOXwZRiGg5uH63i2q2m+0MPN/7HdOJbM4/BgVV9e8553rZIXrOOXne9TsWIBDwHh7k0Y31KbiD4TpNulO23GEFqraPYXqMOhPCouExQDHE=,iv:r4xOexw6qfnM9mhtYGwsEaKAcRptoezZAiqkN2E2xJY=,tag:0QY8sGohMSLoNuUbtXEUTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
