apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5cCkKAON+xJPIIqsnqBddzSFvMkS1jnXa7UzxH1SC/k=,iv:4ZvnUszeulQqycOxDhNe5otRskimJoy0uQBxRrTXR1U=,tag:QNOheN4Zt8Cs1EpwFqFr8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN2h0SDR2Nktxd2VHdFlh
            bko4L215aSsrb3VXNjJSS0szN2cwZ1ZPMWs4CjJIYnp2clhuK1hNdXhaSWdCSEtk
            dlBrVGpmSFhBVkNnQkxCYVJ6Q295RWMKLS0tIE9oTjR0VUM4ZHcwaW1OamQ5Q1d5
            QUY3ckJYZWhVWklNSnptRjNqYS9qancKlJpRq4OqlEoBy8Pp5q7VKQkiEAgyprDB
            Bqx6GKIIkckPJ+K1Ba4I5UhxDEMs8lQ2k9IwpWDYsnZwVQnVp30c5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T14:07:17Z"
    mac: ENC[AES256_GCM,data:1p3v5ppp1Ob/iPTa+z9LBRNnSXa0sadRBmnQ1AMafVoQ4+7t1NsP5XOcShYWt/rLLK5KzEq8FCwgEI05lnOIKZOye73TbbS+2bsKcf4WrmWhBq7wt3hpZgbEAttAdFL22wAcbTf43fQj+T8VX0ax4CfSlGhwJYseaVWXf3ZqkJQ=,iv:rzxnJEiUV1jHB1bUvnubSfYhxA+pd2QtpOXsvDGjMHE=,tag:QonkdK0vwDmZPTvf0InrHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
