apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:CSgBR80SZdYm/EG10EJ+6x59wSQWECQVwyvr/Ra0QxU=,iv:CsJUacXQyUkPnemh1tYqICssrNv5wF2qZEdLpcsHml4=,tag:yiHD1WLHew4FL9wqo/2EYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa3VGcmFhUzRFWTMzbVFi
            bTRZQm8xMmp6UnpGci9zWmZpVHN4NFhNc0F3Ci9MWGZTRUJ5U0pGdmlTdzZJRVhY
            ZzVRYVZhc0l6NnlWSmJSZFREYmkxbTgKLS0tIDhPeFdjSzNjcFpuczY4MGZDTDRX
            K3dQTExuYTMrWEZsYlMwRnVWV2NpNncKKXyDqbSW4N7owYMWnM7lg8y7VbDoj3p+
            57jsF2TVY1s+hseynFIceWRmWMQK/0VC3RIDvdjapE38HN5+cMxdpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T14:32:00Z"
    mac: ENC[AES256_GCM,data:P2S35+b1zFnxr34VmFYbzsd03FXyt+Crtugcct+Kb7rH8hXnKK/MyTimSZxda/JDQ+Wd4BEeTkV6MeFIYRng4C+L9iaNYnSy+RMiGDrdM/RqiCVeU27SNV0WT90+z1Hh310PVoNr3U2c6ZbKAref5kUd4o/N0T6fr24Zu2FZuaM=,iv:FH7a5Pfts/FBY7VqzctynP/D83QniEFGDi7cSczro54=,tag:iOfuR3+wdu0zXzdT+KdI9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
