apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:rhzyvn9tX3cmZOoIkF2PUPlXkEUgNWMyEFCuT2N+SSzaD7OEZrynbA==,iv:s37ciW2Ebf94ReF1xa2O1Y0eAc2U+mEMmXNqamIkIBs=,tag:cOImisTYXudt99hqy6Z7Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUkIwcDNNV2JNQkJaaU5E
            YUl5MUhVQk5WdWhWelk1MUhvdkhNajVQNVQ0CkI5VnlmbkppTTlQOHFxRGl0d3JB
            cU9EQzZtUHBtMHF3RTVLdW1sM2p1MUEKLS0tIFAycTIwemhzZEcvYndsK09qZTFE
            bmlkazFGUFhPS1lRdjk1ak84ZmtNdFEK1/WHcjtXX5hItnwZud05CmkNVfKm62i6
            gjBKZvJrH2jVubF9/Eyxfbo/mgur5PX9mHKqiVpnc15zQwNrxVW9aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T14:32:00Z"
    mac: ENC[AES256_GCM,data:nvDOMqwfRzKwh6SAP6rtpvISfzI1OdJERmMz2wiRNs8oKBejCaY2f6Q9PLj063rfP4H54UEDH4hoJZrApaZjsVB+jW1LL+3E5gdvMliRbU2S8kUsc3C4PC25nFHskg1qMHnAlPZgGMKFgmSl4IQU1xjUHOtl7FCoAOYeybkq37g=,iv:VgzKJlKsnEpfUvSiZI7NE2yv3qugrHCbKz62vMzTpI8=,tag:ERSgc5l3tlO1I9nXCGYm9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
