apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:/jeidDcuwCEWSDBk3/0BZlADEHUETWuz6lbCggl7Jkil8/RqJYa2oQ==,iv:oCyqoeXajsnGDfvncqnaBP1oP8Xi2T7WMQVYEoDKZdQ=,tag:jmKuKQGNK9PEXSahIUgNmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHdBT05YZTRrR2FuV242
            NTZYVTBEcXBsUy9WNUk0c1dtL0lKMmJTREI4ClZLYmZxOHBRQmZnZHp2OEErU2Zs
            QWZtYkFFcHhYQU5ma1g3RS9mZTRxSk0KLS0tIHNNMmc0SnBlLzVoanRNbzczYVgv
            emdkY2hZUkN6c25MTzJUTEs0TFJHMjgK5W9hrzdcPXRSbPsZMP6j6AAZ0oYdxNq2
            U8EcK6PVDTUqrH6iJoP1kCRqBfAPFj1va/5mpe8JNcmnxMBHE+jVxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T14:36:17Z"
    mac: ENC[AES256_GCM,data:2QSMma+pC0DZGyaDNdiLF0baWenQkPfmnAP4uRsU8p0Xl09NA3+aNjDAuzE1RskLTHN/LkgUj3OYwxCaaLa2brn1Ek8iAKZMQVkO8giCIjRZHtAjErF80U2uB4i/aiaXgr5rgc0MGttUvT7wkqH1ro7YqhX2WKOIPSxIHshLXWA=,iv:p9140v2eE0Aoz/ypRwIHfVG1i11geimVV8zU99uioRc=,tag:ZxyLyiGBZXl22u8AsxatSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
