apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4zP2J7qpDn5TjMrsfdBQ9iJF96KYp7fy1lNrI6l3TuSwM8F2dg9+lQ==,iv:gRAY9g+xKkiZhTfQ6YdHX4HoEoxUtVg3IFx9tMRyuno=,tag:sUk/7A8voyCbU0v/64AFXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14q68rfp3s6sgy7kwa2wvvx5psfeda3vapek3ar099wxd3hpqy4pss2e9xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV0tBdzlUZFVrakFEU1hn
            SWM2Zk5PcHJrV1FtTnpOaEFXU2RTNm1QZVNBCkNhV2xmTDhlcDNFY0lLYUxXcTM0
            Wk15QlY0MHlsZnUwc2RubEdLRHNac3cKLS0tICtLbHRlWVh3cmFDTEVMdVpkbVVu
            NFdydkRLWDVqVW1ZSEJxY0hUMWdITVUKwYregE8jHCuTJYssSNoSupIPVATbbkyd
            QZ6apnaNVYiUth2N02dzWZUVbOKqtkoMZ+edtGYtZi0d1L3GvqmTdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T14:07:17Z"
    mac: ENC[AES256_GCM,data:37+nKv9QBkU82tVgOpnABZourkwXoHhCRYMqWQ9w1Qp+52MjMSWrUc2y2jW48Clljx02XfhGCZ8nusnXsBsVfgWzxYgorpIclflTY5xHa8NxHPAVU74ckN8Balkqe2uLqfVAkt/ndlfyT1YZad3ou1FXc3acDi8AFsZ0tvka7vo=,iv:if35qqEY1PhzUboYYo4DosYDrel3cIjqR86/6/6+D9o=,tag:JaAfmtwgxSYBvV0bSxrmhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
